# -*- coding: utf-8 -*-
"""Cópia de Extrator_DataJud.v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19BWoTpd6nBtxJynZDfmGOw9muYkRZCen
"""



"""# Programa para Extração de Dados do DATAJUD - TRF1

## Visão Geral do Programa
O programa realiza as seguintes etapas:

- Configura os parâmetros de busca (tribunal, assunto, período)
- Consulta a API do DATAJUD usando paginação com search_after
- Respeita o rate limit (≤ 120 req/min) com sleep e backoff exponencial
- Processa os dados JSON aninhados em formato tabular
- Exporta para Excel (.xlsx)
"""

# =============================================================================
# CÉLULA 1: INSTALAÇÃO DAS DEPENDÊNCIAS
# =============================================================================
# Execute esta célula primeiro para instalar as bibliotecas necessárias

!pip install requests pandas openpyxl -q

print("✅ Dependências instaladas com sucesso!")

# =============================================================================
# CÉLULA 2: EXTRATOR DATAJUD - TODOS OS TRFs (2021-2026)
# =============================================================================
"""
Extrai processos de Contratos Bancários (TPU 9607) de todos os TRFs
Período: 2021 a 2026
Gera planilha Excel consolidada com todos os resultados
"""

import requests
import json
import pandas as pd
import time
from datetime import datetime

# =============================================================================
# CONFIGURAÇÕES
# =============================================================================

API_KEY = "cDZHYzlZa0JadVREZDJCendQbXY6SkJlTzNjLV9TRENyQk1RdnFKZGRQdw=="

ENDPOINTS = {
    "TRF1": "https://api-publica.datajud.cnj.jus.br/api_publica_trf1/_search",
    "TRF2": "https://api-publica.datajud.cnj.jus.br/api_publica_trf2/_search",
    "TRF3": "https://api-publica.datajud.cnj.jus.br/api_publica_trf3/_search",
    "TRF4": "https://api-publica.datajud.cnj.jus.br/api_publica_trf4/_search",
    "TRF5": "https://api-publica.datajud.cnj.jus.br/api_publica_trf5/_search",
    "TRF6": "https://api-publica.datajud.cnj.jus.br/api_publica_trf6/_search",
}

# -----------------------------------------------------------------------------
# PARÂMETROS DE BUSCA
# -----------------------------------------------------------------------------

# Código do assunto TPU: 9607 = Contratos Bancários
CODIGO_ASSUNTO = 9607

# Anos a consultar
ANOS = [2021, 2022, 2023, 2024, 2025, 2026]

# Registros por página (máximo 10000)
TAMANHO_PAGINA = 500

# Delay entre requisições (segundos) - respeita rate limit 120/min
DELAY_REQUISICAO = 0.6

# Arquivo de saída
ARQUIVO_SAIDA = "datajud_contratos_bancarios_TRFs_2021_2026.xlsx"

# =============================================================================
# FUNÇÕES
# =============================================================================

def fazer_requisicao(url, payload, tentativa=1, max_tentativas=5):
    """Faz requisição à API com retry e backoff exponencial."""
    headers = {
        'Authorization': f'ApiKey {API_KEY}',
        'Content-Type': 'application/json'
    }

    try:
        response = requests.post(url, headers=headers, data=json.dumps(payload), timeout=60)

        if response.status_code == 200:
            return response.json()
        elif response.status_code == 429 or response.status_code >= 500:
            if tentativa < max_tentativas:
                tempo_espera = (2 ** tentativa)
                print(f"      ⚠️ Erro {response.status_code}. Retry em {tempo_espera}s...")
                time.sleep(tempo_espera)
                return fazer_requisicao(url, payload, tentativa + 1, max_tentativas)
        else:
            print(f"      ❌ Erro {response.status_code}: {response.text[:200]}")
            return None
    except Exception as e:
        if tentativa < max_tentativas:
            time.sleep(2 ** tentativa)
            return fazer_requisicao(url, payload, tentativa + 1, max_tentativas)
        print(f"      ❌ Erro de conexão: {e}")
        return None


def consulta_diagnostico(url, tribunal):
    """
    Faz consultas de diagnóstico para verificar volumes totais.
    Ajuda a identificar se o filtro de assunto está funcionando corretamente.
    """
    headers = {
        'Authorization': f'ApiKey {API_KEY}',
        'Content-Type': 'application/json'
    }

    print(f"\n   🔍 Diagnóstico {tribunal}:")

    # Query 1: Total de processos em 2024 (sem filtro de assunto)
    payload_total = {
        "size": 0,
        "query": {
            "bool": {
                "filter": [
                    {"range": {"dataAjuizamento": {"gte": "2024-01-01", "lte": "2024-12-31"}}},
                    {"term": {"nivelSigilo": 0}}
                ]
            }
        }
    }

    resp = requests.post(url, headers=headers, data=json.dumps(payload_total), timeout=30)
    if resp.status_code == 200:
        total = resp.json().get("hits", {}).get("total", {}).get("value", 0)
        print(f"      • Total de processos em 2024 (todos assuntos): {total:,}")

    # Query 2: Com o filtro de assunto 9607
    payload_assunto = {
        "size": 0,
        "query": {
            "bool": {
                "must": [
                    {"match": {"assuntos.codigo": CODIGO_ASSUNTO}}
                ],
                "filter": [
                    {"range": {"dataAjuizamento": {"gte": "2024-01-01", "lte": "2024-12-31"}}},
                    {"term": {"nivelSigilo": 0}}
                ]
            }
        }
    }

    resp = requests.post(url, headers=headers, data=json.dumps(payload_assunto), timeout=30)
    if resp.status_code == 200:
        total = resp.json().get("hits", {}).get("total", {}).get("value", 0)
        print(f"      • Com assunto {CODIGO_ASSUNTO} (Contratos Bancários): {total}")

    # Query 3: Busca textual por "bancário" no nome do assunto
    payload_texto = {
        "size": 0,
        "query": {
            "bool": {
                "must": [
                    {"match": {"assuntos.nome": "bancário"}}
                ],
                "filter": [
                    {"range": {"dataAjuizamento": {"gte": "2024-01-01", "lte": "2024-12-31"}}},
                    {"term": {"nivelSigilo": 0}}
                ]
            }
        }
    }

    resp = requests.post(url, headers=headers, data=json.dumps(payload_texto), timeout=30)
    if resp.status_code == 200:
        total = resp.json().get("hits", {}).get("total", {}).get("value", 0)
        print(f"      • Busca textual 'bancário' no nome do assunto: {total}")

    time.sleep(DELAY_REQUISICAO * 3)


def extrair_processos(url, tribunal, ano):
    """
    Extrai processos de um tribunal/ano específico usando paginação search_after.
    """
    data_inicio = f"{ano}-01-01"
    data_fim = f"{ano}-12-31"

    processos = []
    pagina = 0
    search_after = None

    while True:
        pagina += 1

        # Monta a query seguindo o padrão da documentação
        payload = {
            "size": TAMANHO_PAGINA,
            "query": {
                "bool": {
                    "must": [
                        {"match": {"assuntos.codigo": CODIGO_ASSUNTO}}
                    ],
                    "filter": [
                        {"range": {"dataAjuizamento": {"gte": data_inicio, "lte": data_fim}}},
                        {"term": {"nivelSigilo": 0}}
                    ]
                }
            },
            "sort": [{"@timestamp": {"order": "asc"}}]
        }

        if search_after:
            payload["search_after"] = search_after

        time.sleep(DELAY_REQUISICAO)
        resposta = fazer_requisicao(url, payload)

        if not resposta:
            break

        hits = resposta.get("hits", {}).get("hits", [])
        total_info = resposta.get("hits", {}).get("total", {})

        # Primeira página: mostra total
        if pagina == 1:
            total_val = total_info.get("value", 0)
            rel = total_info.get("relation", "eq")
            sufixo = "+" if rel == "gte" else ""
            print(f"      {tribunal} {ano}: {total_val}{sufixo} processos encontrados")

            if total_val == 0:
                break

        if not hits:
            break

        # Adiciona os processos
        for hit in hits:
            proc = hit.get("_source", {})
            proc["_tribunal_consulta"] = tribunal  # Marca o tribunal
            proc["_ano_consulta"] = ano            # Marca o ano
            processos.append(proc)

        # Prepara próxima página
        search_after = hits[-1].get("sort")
        if not search_after or len(hits) < TAMANHO_PAGINA:
            break

    return processos


def processar_dataframe(processos):
    """Converte lista de processos para DataFrame tabular."""
    if not processos:
        return pd.DataFrame()

    print(f"\n🔄 Processando {len(processos)} processos...")

    dados = []
    for proc in processos:
        linha = {
            # Metadados da consulta
            "tribunal_fonte": proc.get("_tribunal_consulta", ""),
            "ano_consulta": proc.get("_ano_consulta", ""),

            # Identificação
            "id": proc.get("id", ""),
            "numeroProcesso": proc.get("numeroProcesso", ""),
            "tribunal": proc.get("tribunal", ""),
            "grau": proc.get("grau", ""),

            # Datas
            "dataAjuizamento": proc.get("dataAjuizamento", ""),

            # Classe
            "classe_codigo": (proc.get("classe") or {}).get("codigo", ""),
            "classe_nome": (proc.get("classe") or {}).get("nome", ""),

            # Assuntos (concatenados)
            "assuntos_codigos": " | ".join(str(a.get("codigo", "")) for a in (proc.get("assuntos") or [])),
            "assuntos_nomes": " | ".join(a.get("nome", "") for a in (proc.get("assuntos") or [])),

            # Órgão julgador
            "orgao_codigo": (proc.get("orgaoJulgador") or {}).get("codigo", ""),
            "orgao_nome": (proc.get("orgaoJulgador") or {}).get("nome", ""),
            "municipio_ibge": (proc.get("orgaoJulgador") or {}).get("codigoMunicipioIBGE", ""),

            # Sistema e formato
            "sistema": (proc.get("sistema") or {}).get("nome", ""),
            "formato": (proc.get("formato") or {}).get("nome", ""),

            # Sigilo
            "nivelSigilo": proc.get("nivelSigilo", ""),

            # Movimentos (resumo)
            "qtd_movimentos": len(proc.get("movimentos") or []),

            # Timestamps
            "ultimaAtualizacao": proc.get("dataHoraUltimaAtualizacao", ""),
            "timestamp": proc.get("@timestamp", ""),
        }

        # Último movimento
        movimentos = proc.get("movimentos") or []
        if movimentos:
            movs_ordenados = sorted(
                [m for m in movimentos if m.get("dataHora")],
                key=lambda x: x.get("dataHora", ""),
                reverse=True
            )
            if movs_ordenados:
                linha["ultimo_mov_data"] = movs_ordenados[0].get("dataHora", "")
                linha["ultimo_mov_nome"] = movs_ordenados[0].get("nome", "")

        dados.append(linha)

    df = pd.DataFrame(dados)

    # Extrai ano do ajuizamento para facilitar análises
    if "dataAjuizamento" in df.columns:
        df["ano_ajuizamento"] = pd.to_datetime(df["dataAjuizamento"], errors="coerce").dt.year

    print(f"✅ DataFrame: {len(df)} linhas × {len(df.columns)} colunas")
    return df


def exportar_excel(df, arquivo):
    """Exporta DataFrame para Excel com formatação."""
    if df.empty:
        print("⚠️ Nenhum dado para exportar.")
        return False

    print(f"\n💾 Salvando: {arquivo}")

    with pd.ExcelWriter(arquivo, engine="openpyxl") as writer:
        # Aba principal com todos os dados
        df.to_excel(writer, sheet_name="Processos", index=False)

        # Aba de resumo
        resumo = df.groupby(["tribunal_fonte", "ano_consulta"]).size().unstack(fill_value=0)
        resumo.to_excel(writer, sheet_name="Resumo")

        # Formatação
        ws = writer.sheets["Processos"]
        ws.freeze_panes = "A2"

    print(f"✅ Arquivo salvo com sucesso!")
    return True


# =============================================================================
# EXECUÇÃO PRINCIPAL
# =============================================================================

def main():
    print("\n" + "=" * 70)
    print("   EXTRATOR DATAJUD - CONTRATOS BANCÁRIOS")
    print("   Todos os TRFs | 2021 a 2026")
    print("=" * 70)

    inicio = datetime.now()
    print(f"\n🚀 Início: {inicio.strftime('%d/%m/%Y %H:%M:%S')}")
    print(f"\n📋 Configuração:")
    print(f"   • Assunto: {CODIGO_ASSUNTO} (Contratos Bancários)")
    print(f"   • Tribunais: TRF1 a TRF6")
    print(f"   • Anos: {min(ANOS)} a {max(ANOS)}")

    # -------------------------------------------------------------------------
    # ETAPA 1: Diagnóstico (apenas TRF1 como amostra)
    # -------------------------------------------------------------------------
    print("\n" + "-" * 70)
    print("📊 ETAPA 1: DIAGNÓSTICO DE VOLUMES")
    print("-" * 70)

    for trf in ["TRF1", "TRF3"]:  # Amostra de 2 TRFs para diagnóstico
        consulta_diagnostico(ENDPOINTS[trf], trf)

    # -------------------------------------------------------------------------
    # ETAPA 2: Extração completa
    # -------------------------------------------------------------------------
    print("\n" + "-" * 70)
    print("📥 ETAPA 2: EXTRAÇÃO DE PROCESSOS")
    print("-" * 70)

    todos_processos = []
    estatisticas = {}

    for tribunal, url in ENDPOINTS.items():
        print(f"\n   🏛️ {tribunal}:")
        estatisticas[tribunal] = {}

        for ano in ANOS:
            processos = extrair_processos(url, tribunal, ano)
            estatisticas[tribunal][ano] = len(processos)
            todos_processos.extend(processos)

    # -------------------------------------------------------------------------
    # ETAPA 3: Processamento e exportação
    # -------------------------------------------------------------------------
    print("\n" + "-" * 70)
    print("📊 ETAPA 3: PROCESSAMENTO E EXPORTAÇÃO")
    print("-" * 70)

    if not todos_processos:
        print("\n⚠️ Nenhum processo encontrado!")
        print("\nPossíveis causas:")
        print("  1. O código de assunto 9607 pode ter poucos processos na Justiça Federal")
        print("  2. A maioria dos processos de 'Contratos Bancários' está na Justiça Estadual")
        print("  3. Os processos podem estar classificados em assuntos 'filhos' mais específicos")
        return None

    df = processar_dataframe(todos_processos)
    exportar_excel(df, ARQUIVO_SAIDA)

    # -------------------------------------------------------------------------
    # RESUMO FINAL
    # -------------------------------------------------------------------------
    fim = datetime.now()
    duracao = fim - inicio

    print("\n" + "=" * 70)
    print("   RESUMO DA EXECUÇÃO")
    print("=" * 70)

    # Tabela de resultados
    print("\n   Processos por Tribunal e Ano:")
    print("   " + "-" * 50)
    print(f"   {'TRF':<8}", end="")
    for ano in ANOS:
        print(f"{ano:>8}", end="")
    print(f"{'TOTAL':>10}")
    print("   " + "-" * 50)

    for tribunal in ENDPOINTS.keys():
        print(f"   {tribunal:<8}", end="")
        total_trib = 0
        for ano in ANOS:
            qtd = estatisticas.get(tribunal, {}).get(ano, 0)
            total_trib += qtd
            print(f"{qtd:>8}", end="")
        print(f"{total_trib:>10}")

    print("   " + "-" * 50)
    print(f"   {'TOTAL':<8}", end="")
    for ano in ANOS:
        total_ano = sum(estatisticas.get(t, {}).get(ano, 0) for t in ENDPOINTS.keys())
        print(f"{total_ano:>8}", end="")
    print(f"{len(todos_processos):>10}")

    print(f"\n   ⏱️ Tempo total: {duracao}")
    print(f"   💾 Arquivo: {ARQUIVO_SAIDA}")
    print("=" * 70)

    # Preview dos dados
    if not df.empty:
        print("\n📋 PRÉVIA DOS DADOS:")
        display(df.head(10))

    return df

# Executa
df_resultado = main()

